import type { BundledPluginTranslationCatalogs } from '@valley/plugin-sdk'

export const generatedCatalogs = {
  "en": {
    "auto.04571e759593": "No frontmatter",
    "auto.0788afd1d0e7": "Missing keys",
    "auto.08353eb6fdd4": "No type field",
    "auto.0e37a97118a4": "Extra keys",
    "auto.122d3c2cf197": "Check: Show status",
    "auto.24b342717bff": "Footer warning when the vault is not right: duplicate file names and notes that deviate from their template.",
    "auto.2b1abac0eede": "Comma-separated folders skipped by both checks.",
    "auto.3f9714e381b4": "Strict filenames",
    "auto.3f9755e92b12": "Warn when a note does not match the template for its type exactly (keys, order and value types).",
    "auto.43b6abbe96be": "Wrong value type",
    "auto.4b5e84be0e45": "Check",
    "auto.5387a0df285c": "Templates folder",
    "auto.572f2ac4595f": "Strict template check",
    "auto.70c6ac4549b3": "Comma-separated file extensions skipped by the filename check. .json and .jsonl are always ignored.",
    "auto.768f9220e68b": "Vault checks clean.",
    "auto.7cd7cd45a31e": "Comma-separated path substrings to skip.",
    "auto.8497c0f895ff": "{{p0}} template issue{{p1}} found — click for details",
    "auto.89e396116977": "Excluded patterns",
    "auto.9456190df480": "{{p0}} duplicate file name{{p1}} — click for details",
    "auto.956d3039f8ba": "Excluded folders",
    "auto.a0432d9e1d11": "Comma-separated frontmatter keys ignored during the template comparison.",
    "auto.c69679958c57": "Template folder location",
    "auto.c7580f8e3d7c": "Wrong key order",
    "auto.cdc7582f2de4": "Warn when two files share the same name (ignoring extension).",
    "auto.d1767c91c535": "Ignored keys",
    "auto.dcb9d121fdf0": "Ignored extensions",
    "auto.e0a836ec9bdd": "Vault-relative folder. Each template defines the schema for its frontmatter \"type\".",
    "auto.e6cb55c694b8": "Unknown type",
    "plugin.check.field.strictNames": "Strict filenames",
    "plugin.check.field.ignoredExtensions": "Ignored extensions",
    "plugin.check.field.strictTemplate": "Strict template check",
    "plugin.check.field.templatesFolder": "Templates folder",
    "plugin.check.field.excludedFolders": "Excluded folders",
    "plugin.check.field.excludedPatterns": "Excluded patterns",
    "plugin.check.field.ignoredKeys": "Ignored keys",
    "plugin.check.desc": "Validates filenames and note templates against your rules and reports problems in the footer.",
    "plugin.check.name": "Check"
  },
  "de": {
    "auto.04571e759593": "Keine Frontsache",
    "auto.0788afd1d0e7": "Fehlende Schlüssel",
    "auto.08353eb6fdd4": "Kein Typfeld",
    "auto.0e37a97118a4": "Zusätzliche Schlüssel",
    "auto.122d3c2cf197": "Check: Status anzeigen",
    "auto.24b342717bff": "Fußzeilenwarnung, wenn der Tresor nicht stimmt: doppelte Dateinamen und Notizen, die von ihrer Vorlage abweichen.",
    "auto.2b1abac0eede": "Durch Kommas getrennte Ordner werden von beiden Prüfungen übersprungen.",
    "auto.3f9714e381b4": "Strenge Dateinamen",
    "auto.3f9755e92b12": "Warnen Sie, wenn eine Notiz hinsichtlich ihres Typs (Schlüssel, Reihenfolge und Werttypen) nicht genau mit der Vorlage übereinstimmt.",
    "auto.43b6abbe96be": "Falscher Werttyp",
    "auto.4b5e84be0e45": "Prüfung",
    "auto.5387a0df285c": "Ordner „Vorlagen“.",
    "auto.572f2ac4595f": "Strenge Vorlagenprüfung",
    "auto.70c6ac4549b3": "Durch Kommas getrennte Dateierweiterungen werden bei der Dateinamenprüfung übersprungen. .json und .jsonl werden immer ignoriert.",
    "auto.768f9220e68b": "Tresorkontrollen sauber.",
    "auto.7cd7cd45a31e": "Durch Kommas getrennte Pfadteilzeichenfolgen, die übersprungen werden sollen.",
    "auto.8497c0f895ff": "{{p0}} Vorlagenproblem{{p1}} gefunden – klicken Sie für Details",
    "auto.89e396116977": "Ausgeschlossene Muster",
    "auto.9456190df480": "{{p0}} doppelter Dateiname{{p1}} – klicken Sie für Details",
    "auto.956d3039f8ba": "Ausgeschlossene Ordner",
    "auto.a0432d9e1d11": "Durch Kommas getrennte Frontmatter-Schlüssel werden beim Vorlagenvergleich ignoriert.",
    "auto.c69679958c57": "Speicherort des Vorlagenordners",
    "auto.c7580f8e3d7c": "Falsche Schlüsselreihenfolge",
    "auto.cdc7582f2de4": "Warnen, wenn zwei Dateien denselben Namen haben (Erweiterung ignorieren).",
    "auto.d1767c91c535": "Ignorierte Schlüssel",
    "auto.dcb9d121fdf0": "Ignorierte Erweiterungen",
    "auto.e0a836ec9bdd": "Vault-relativer Ordner. Jede Vorlage definiert das Schema für ihren Frontmatter-„Typ“.",
    "auto.e6cb55c694b8": "Unbekannter Typ",
    "plugin.check.field.strictNames": "Strenge Dateinamen",
    "plugin.check.field.ignoredExtensions": "Ignorierte Erweiterungen",
    "plugin.check.field.strictTemplate": "Strenge Vorlagenprüfung",
    "plugin.check.field.templatesFolder": "Vorlagenordner",
    "plugin.check.field.excludedFolders": "Ausgeschlossene Ordner",
    "plugin.check.field.excludedPatterns": "Ausgeschlossene Muster",
    "plugin.check.field.ignoredKeys": "Ignorierte Schlüssel",
    "plugin.check.desc": "Prüft Dateinamen und Notizvorlagen gegen deine Regeln und meldet Probleme in der Fußzeile.",
    "plugin.check.name": "Prüfen"
  },
  "es": {
    "auto.04571e759593": "Sin front-asunto",
    "auto.0788afd1d0e7": "llaves faltantes",
    "auto.08353eb6fdd4": "Sin campo de tipo",
    "auto.0e37a97118a4": "llaves adicionales",
    "auto.122d3c2cf197": "Check: Mostrar estado",
    "auto.24b342717bff": "Advertencia en el pie de página cuando la bóveda no es correcta: nombres de archivos duplicados y notas que se desvían de su plantilla.",
    "auto.2b1abac0eede": "Ambas comprobaciones omitieron las carpetas separadas por comas.",
    "auto.3f9714e381b4": "Nombres de archivos estrictos",
    "auto.3f9755e92b12": "Advierte cuando una nota no coincide exactamente con la plantilla para su tipo (claves, orden y tipos de valor).",
    "auto.43b6abbe96be": "Tipo de valor incorrecto",
    "auto.4b5e84be0e45": "Comprobación",
    "auto.5387a0df285c": "Carpeta de plantillas",
    "auto.572f2ac4595f": "Control estricto de la plantilla",
    "auto.70c6ac4549b3": "Extensiones de archivos separadas por comas omitidas por la verificación del nombre de archivo. .json y .jsonl siempre se ignoran.",
    "auto.768f9220e68b": "La bóveda está limpia.",
    "auto.7cd7cd45a31e": "Subcadenas de ruta separadas por comas que se deben omitir.",
    "auto.8497c0f895ff": "Se encontró {{p0}} problema de plantilla{{p1}}: haga clic para obtener más detalles",
    "auto.89e396116977": "Patrones excluidos",
    "auto.9456190df480": "{{p0}} nombre de archivo duplicado{{p1}}: haz clic para obtener más detalles",
    "auto.956d3039f8ba": "Carpetas excluidas",
    "auto.a0432d9e1d11": "Las claves iniciales separadas por comas se ignoran durante la comparación de plantillas.",
    "auto.c69679958c57": "Ubicación de la carpeta de plantillas",
    "auto.c7580f8e3d7c": "Orden de claves incorrecto",
    "auto.cdc7582f2de4": "Advierte cuando dos archivos comparten el mismo nombre (ignorando la extensión).",
    "auto.d1767c91c535": "Claves ignoradas",
    "auto.dcb9d121fdf0": "Extensiones ignoradas",
    "auto.e0a836ec9bdd": "Carpeta relativa al almacén. Cada plantilla define el esquema para su \"tipo\" de tema inicial.",
    "auto.e6cb55c694b8": "tipo desconocido",
    "plugin.check.field.strictNames": "Nombres de archivo estrictos",
    "plugin.check.field.ignoredExtensions": "Extensiones ignoradas",
    "plugin.check.field.strictTemplate": "Comprobación estricta de plantillas",
    "plugin.check.field.templatesFolder": "Carpeta de plantillas",
    "plugin.check.field.excludedFolders": "Carpetas excluidas",
    "plugin.check.field.excludedPatterns": "Patrones excluidos",
    "plugin.check.field.ignoredKeys": "Claves ignoradas",
    "plugin.check.desc": "Valida los nombres de archivo y las plantillas de notas según tus reglas e informa de los problemas en el pie.",
    "plugin.check.name": "Comprobar"
  },
  "fr": {
    "auto.04571e759593": "Pas de front",
    "auto.0788afd1d0e7": "Clés manquantes",
    "auto.08353eb6fdd4": "Aucun champ de type",
    "auto.0e37a97118a4": "Clés supplémentaires",
    "auto.122d3c2cf197": "Check: afficher l’état",
    "auto.24b342717bff": "Avertissement de pied de page lorsque le coffre-fort n'est pas correct : noms de fichiers en double et notes qui s'écartent de leur modèle.",
    "auto.2b1abac0eede": "Dossiers séparés par des virgules ignorés par les deux vérifications.",
    "auto.3f9714e381b4": "Noms de fichiers stricts",
    "auto.3f9755e92b12": "Avertir lorsqu'une note ne correspond pas exactement au modèle pour son type (types de clés, d'ordre et de valeur).",
    "auto.43b6abbe96be": "Mauvais type de valeur",
    "auto.4b5e84be0e45": "Vérification",
    "auto.5387a0df285c": "Dossier modèles",
    "auto.572f2ac4595f": "Vérification stricte du modèle",
    "auto.70c6ac4549b3": "Extensions de fichiers séparées par des virgules ignorées par la vérification du nom de fichier. .json et .jsonl sont toujours ignorés.",
    "auto.768f9220e68b": "Les chèques du coffre-fort sont propres.",
    "auto.7cd7cd45a31e": "Sous-chaînes de chemin séparées par des virgules à ignorer.",
    "auto.8497c0f895ff": "{{p0}} problème de modèle{{p1}} détecté – cliquez pour plus de détails",
    "auto.89e396116977": "Modèles exclus",
    "auto.9456190df480": "{{p0}} nom de fichier en double{{p1}} – cliquez pour plus de détails",
    "auto.956d3039f8ba": "Dossiers exclus",
    "auto.a0432d9e1d11": "Clés de premier plan séparées par des virgules ignorées lors de la comparaison des modèles.",
    "auto.c69679958c57": "Emplacement du dossier de modèles",
    "auto.c7580f8e3d7c": "Mauvaise commande de clé",
    "auto.cdc7582f2de4": "Avertir lorsque deux fichiers partagent le même nom (en ignorant l'extension).",
    "auto.d1767c91c535": "Clés ignorées",
    "auto.dcb9d121fdf0": "Extensions ignorées",
    "auto.e0a836ec9bdd": "Dossier relatif au coffre-fort. Chaque modèle définit le schéma pour son « type » de premier plan.",
    "auto.e6cb55c694b8": "Type inconnu",
    "plugin.check.field.strictNames": "Noms de fichiers stricts",
    "plugin.check.field.ignoredExtensions": "Extensions ignorées",
    "plugin.check.field.strictTemplate": "Vérification stricte des modèles",
    "plugin.check.field.templatesFolder": "Dossier des modèles",
    "plugin.check.field.excludedFolders": "Dossiers exclus",
    "plugin.check.field.excludedPatterns": "Motifs exclus",
    "plugin.check.field.ignoredKeys": "Clés ignorées",
    "plugin.check.desc": "Valide les noms de fichiers et les modèles de notes selon vos règles et indique les problèmes en pied de page.",
    "plugin.check.name": "Vérifier"
  },
  "zh-CN": {
    "auto.04571e759593": "没有前置问题",
    "auto.0788afd1d0e7": "钥匙丢失",
    "auto.08353eb6fdd4": "无类型字段",
    "auto.0e37a97118a4": "额外的钥匙",
    "auto.122d3c2cf197": "Check: 显示状态",
    "auto.24b342717bff": "当 Vault 不正确时，页脚警告：重复的文件名和注释偏离其模板。",
    "auto.2b1abac0eede": "两项检查都会跳过以逗号分隔的文件夹。",
    "auto.3f9714e381b4": "严格的文件名",
    "auto.3f9755e92b12": "当注释与模板的类型（键、顺序和值类型）不完全匹配时发出警告。",
    "auto.43b6abbe96be": "值类型错误",
    "auto.4b5e84be0e45": "检查",
    "auto.5387a0df285c": "模板文件夹",
    "auto.572f2ac4595f": "严格模板检查",
    "auto.70c6ac4549b3": "文件名检查跳过以逗号分隔的文件扩展名。 .json 和 .jsonl 始终被忽略。",
    "auto.768f9220e68b": "Vault 检查干净。",
    "auto.7cd7cd45a31e": "要跳过的以逗号分隔的路径子字符串。",
    "auto.8497c0f895ff": "发现{{p0}}模板问题{{p1}} - 点击查看详细信息",
    "auto.89e396116977": "排除的模式",
    "auto.9456190df480": "{{p0}}重复文件名{{p1}} — 点击查看详细信息",
    "auto.956d3039f8ba": "排除的文件夹",
    "auto.a0432d9e1d11": "在模板比较期间忽略逗号分隔的 frontmatter 键。",
    "auto.c69679958c57": "模板文件夹位置",
    "auto.c7580f8e3d7c": "按键顺序错误",
    "auto.cdc7582f2de4": "当两个文件共享相同名称（忽略扩展名）时发出警告。",
    "auto.d1767c91c535": "忽略的键",
    "auto.dcb9d121fdf0": "忽略的扩展",
    "auto.e0a836ec9bdd": "保管库相对文件夹。每个模板都定义了其 frontmatter“类型”的架构。",
    "auto.e6cb55c694b8": "未知类型",
    "plugin.check.field.strictNames": "严格文件名",
    "plugin.check.field.ignoredExtensions": "忽略的扩展名",
    "plugin.check.field.strictTemplate": "严格模板检查",
    "plugin.check.field.templatesFolder": "模板文件夹",
    "plugin.check.field.excludedFolders": "排除的文件夹",
    "plugin.check.field.excludedPatterns": "排除的模式",
    "plugin.check.field.ignoredKeys": "忽略的键",
    "plugin.check.desc": "按你的规则校验文件名和笔记模板，并在页脚报告问题。",
    "plugin.check.name": "检查"
  }
} satisfies BundledPluginTranslationCatalogs
